### PR TITLE
[typescript] Result of hoc withRouter should not require props provided by it

### PR DESCRIPTION
**Pull request by rosskevin**

### CODE REVIEW

**Comment by jquense** [comment]
looks good, can you add a test exercising the type in types/text.jsx

**Comment by rosskevin** [comment]
It was already exercised, not sure why it was not erroring.  https://github.com/4Catalyzer/found/blob/master/test/typescript/MainPage.tsx#L6

**Comment by taion** [comment]
@jquense Should we merge as-is, then, or do you want to look at the test?

**Comment by rosskevin** [comment]
I'll take another look at the script.

**Comment by rosskevin** [comment]
Whomever added dtslint ignored the existing test files.

**Comment by rosskevin** [comment]
Ok, original typescript tests added and fixed up based on the dtslint rules.  Should be good to go.

**Comment by taion** [comment]
@jquense Can you take another look? If it's good, I'll cut a release.

**Comment by taion** [comment]
released in v0.3.17

**Pull request merged**
