### PR TITLE
[feedback] named components

### PR DESCRIPTION
**Pull request by itajaja**
This is a very simple implementation, I am sure I might be missing something. Especially I don't know how to make the api play nicely with `render` prop

### CODE REVIEW

**Comment by taion** [comment]
Instead of doing it this way – why don't we allow `childRoutes` to take an object instead of just an array? Something like

```js
const route = {
  path: '/foo',
  Component: FooComponent,
  childRoutes: {
    bar: [
      { path: '/bar1' },
      { path: '/bar2' },
    ],
    baz: [
      { path: '/baz' },
    ],
  },
};
```

This would allow more flexibility, and we could look for a way to be more systematic.

**Comment by itajaja** [comment]
how can that be translated to JSX?

**Comment by taion** [comment]
```js
<Route
  path="/foo"
  Component={Foo}
  childRoutes={{
    bar: // ...,
    baz: // ...,
  }}
/>
```

Not the cleanest, but (1) it works, (2) it's more flexible.

**Comment by itajaja** [comment]
why is it more flexible? also, that configuration means you'll have to specify a route more times for each "name", instead of specifying each "name" more times for each times. I think the latter is more manageable when you have more complex and nested routes, because one route definition would contain all the related components together instead of being spread in different places

**Comment by taion** [comment]
It's more flexible because `bar` and `baz` there can have separate children.

**Comment by itajaja** [comment]
but the sets of childRoutes paths will not be totally disjoint, and most likely for the same level of route will be the same. Is there a route configuration that would be possible only with that API and not with this PR's one?

**Comment by taion** [comment]
It's even more important when they aren't disjoint.

```js
{
  foo: [
    { path: '/bar/:whatever' },
  ],
  baz: [
    { path: '/bar/baz' },
    { path: '/bar/qux' },
  ],
}
```

also easier implementation-wise on the resolvers – just expose something to flat map, then reshape the route match

**Comment by taion** [comment]
So practically the use case is something like:

```js
const route = (
  <Route
    Component={MainPage}
    childRoutes={{
      sidebar: (
        <Route>
          <Route path="section1/*?" Component={Sidebar1} />
          <Route path="section2/*?" Component={Sidebar2} />
        </Route>
      ),
      main: (
        <Route>
          <Route path="section1">
            <Route path="page1" />
            <Route path="page2" />
          </Route>
          <Route path="section2">
            <Route path="page3" />
          </Route>
        </Route>
      ),
    }}
  />
);
```

**Comment by taion** [comment]
The tricky thing is that:

```js
<Route Component={MainPage}>
  <Route path="section1" Components={{sidebar: Sidebar1, main: Main1}} />
</Route>
```

becomes a little tricker, since if you add an intervening `<Route>`, `<MainPage>` no longer gets `sidebar` and `main` as props directly, at least with a naive implementation.

I think this can be resolved, though.

**Comment by hannesj** [comment]
@taion That would make much more sense at least for our implementation where we mostly have one of the named components (main content) changing per route and headers/sidebar/meta remaining the same for different sub-routes.

**Comment by taion** [comment]
Another API option:

```js
<Route path="/" Component={App}>
  <RouteGroup
    path="foo"
    nav={<Route Component={FooNav} />}
    main={(
      <Route>
        <Route Component={FooMain} />
        <Route path="1" Component={Foo1} />
      </Route>
    )}
  />
  <RouteGroup
    path="bar"
    nav={<Route Component={BarNav} />}
    main={(
      <Route>
        <Route Component={BarMain} />
        <Route path="1" Component={Bar1} />
      </Route>
    )}
  />
```

This would give a nice principled way to inject `nav` and `main` as props into `<App>`.

**Comment by itajaja** [comment]
@taion the second api option wouldn't have a clean non-jsx alternative. I'd go with the `childRoute` impl or something like:

```
const route = (
  <Route
    Component={MainPage}
  >
    <Route group="sidebar">
        <Route>
          <Route path="section1/*?" Component={Sidebar1} />
          <Route path="section2/*?" Component={Sidebar2} />
        </Route>
    </Route>
    <Route group="main">
      <Route>
        <Route path="section1">
          <Route path="page1" />
          <Route path="page2" />
        </Route>
        <Route path="section2">
          <Route path="page3" />
        </Route>
      </Route>
    </Route>
  </Route>
);
```

instead of `group` could be `name` (maybe conflicting with named routes...), `placeholder`, `section`...

**Comment by taion** [comment]
Remember that components control how they translate to/from JSX or not. It'd just be:

```js
new RouteGroup({
  path: '/foo',
  main: // ...,
});
```

**Comment by itajaja** [comment]
so a plain object for a normal route, and an instance of `RouteGroup` for the route group? it's a little bit asymmetrical, but it's probably ok

**Comment by taion** [comment]
I'm not sure what you mean. Isn't it a `RouteGroup` in both cases?

**Comment by itajaja** [comment]
let me get this straight, This

```jsx
<Route path="/" Component={App}>
  <RouteGroup
    path="foo"
    nav={<Route Component={FooNav} />}
    main={(
      <Route>
        <Route Component={FooMain} />
        <Route path="1" Component={Foo1} />
      </Route>
    )}
  />
  <RouteGroup
    path="bar"
    nav={<Route Component={BarNav} />}
    main={(
      <Route>
        <Route Component={BarMain} />
        <Route path="1" Component={Bar1} />
      </Route>
    )}
  />
</Route>
```

would be translated into something like

```js
{
  path: '/',
  Component: App,
  children: [
    new RouteGroup({ path: 'foo', ...}),
    new RouteGroup({ path: 'bar', ...}),
  ],
};
```

correct? another problem with that is the name collision between props and group names

**Comment by taion** [comment]
We can provide a fallback if someone _really_ wants to name a route group "path".

**Comment by taion** [comment]
Closing this out for now, since we're not going to be going with this approach.

**Pull request closed without merging**
