### PR TITLE
feat: Use our own context

### PR DESCRIPTION
**Pull request by taion**
BREAKING CHANGE: Remove custom connector utilities

Closes https://github.com/4Catalyzer/found/issues/242

### CODE REVIEW

**Comment by taion** [comment]
This would allow `useContext(RouterContext)`, though I wonder if we should expose our own `useRouter` hook.

**Comment by taion** [comment]
@jquense Any thoughts here?

**Comment by jquense** [comment]
SHHHHIIIIIIP IIIIIITTTT

**Comment by taion** [comment]
@jquense should we ship a `useRouter`, or is `useContext(RouterContext)` the recommended approach?

**Comment by jquense** [comment]
I think useRouter since you don't need to expose the context otherwise, since router is the provider

**Comment by taion** [comment]
I actually want to expose the context. It will make testing easier. But I think `useRouter` is probably a neater API.

**Pull request merged**
