### PR TITLE
pathToRegexp.keys is not always set

### PR DESCRIPTION
**Pull request by staylor**
On home route, when no params are present to map, this property cannot be iterated

### CODE REVIEW

**Comment by taion** [comment]
Which browser are you seeing this on?

```
$ node
> const pathToRegexp = require('path-to-regexp');
undefined
> const regexp = pathToRegexp('/home', { end: false })
undefined
> regexp.keys
[]
```

**Comment by staylor** [comment]
when nested path is "/" on Chrome

**Comment by staylor** [comment]
Here's my simple route config:

```js
export const routeConfig = makeRouteConfig(
  <Route
    path="/"
    Component={App}
    query={AppQuery}
    prepareVariables={params => ({
      ...params,
      menuID: "TmF2TWVudToy",
      sidebarID: "U2lkZWJhcjpzaWRlYmFyLTE="
    })}
  >
    <Route path="post/:id" Component={Single} query={SingleQuery} />
    <Route
      path="/"
      Component={Home}
      query={HomeQuery}
      prepareVariables={params => ({
        ...params,
        readThisID: "Q2F0ZWdvcnk6Mw==",
        watchThisID: "Q2F0ZWdvcnk6NA==",
        listenToThisID: "Q2F0ZWdvcnk6NQ=="
      })}
    />
  </Route>
);
```

**Comment by taion** [comment]
Can you log the specific pattern that causes this problem? I can't seem to reproduce this on Node.

BTW, in the 2nd nested route (the one you have for `Home`), you shouldn't need to specify `path` at all.

The reason I think this might not be the root issue is that the examples use very similar param-less route patterns, and last I checked they still worked on Chrome: https://github.com/4Catalyzer/found/blob/master/examples/basic-jsx/src/index.js#L58-L89

**Comment by staylor** [comment]
Removed the path for nested Route:

server: `{ /^(?:\/(?=$))?(?=\/|$)/i keys: [] }`
client: `/^\/?$/i`

**Comment by taion** [comment]
I think this is a bug in your build process – that looks like you've ended up with `path-to-regexp@0.1.7` in your client build somehow.

**Comment by staylor** [comment]
`express` loads `0.1.7` - not sure if this is a bug in Yarn or https://github.com/NYTimes/kyt

**Comment by taion** [comment]
It's hard to say for sure. If you're building your client bundle from the same Node checkout, make sure that you're not overly-aggressively deduplicating in webpack. That or try wiping and reinstalling your dependencies.

**Comment by staylor** [comment]
I got it to work by explicitly depending on `path-to-regexp` in my project, I'll do some more digging on our webpack build

**Comment by taion** [comment]
Going to add https://github.com/4Catalyzer/found/pull/92 to warn on this, since I think this bit me as well a while ago and took longer than it should have to track down

**Pull request closed without merging**
