### PR TITLE
Add yarn, flow-bin, and minimal types

### PR DESCRIPTION
**Pull request by steida**

### CODE REVIEW

**Comment by steida** [comment]
I didn't touch code except for jsx and server index.js, where you are using some not yet standard ES syntax.

**Comment by steida** [comment]
Why `any` everywhere? It simulates deprecated weak mode.

https://flowtype.org/docs/existing.html#dealing-with-a-large-number-of-type-errors

**Comment by taion** [comment]
What's the benefit of using Flow here? I feel like since a lot of people don't use Flow, that this increases the barrier to entry for contributing or understanding the code here.

**Comment by steida** [comment]
Anyone can contribute. New file without `// @flow` will not be checked, the current file can be modified easily because types are inferred. Even without explicit types, flow helps a lot. It provides real autocomplete, detects mistakes, provides code navigation.

You are experienced developer, so you are not making a silly errors, still it can happen.

**Comment by steida** [comment]
Note flowtype adoption is gradual. We can add types later, and they will serve as great documentation for props, args, etc. 2017 is year of Flowtype.

**Comment by steida** [comment]
Also, yarn.lock is great. Really.

**Comment by taion** [comment]
I'm not sure about that on the Flow side. If somebody not familiar with Flow wants to submit a PR to an existing file, what is he or she to do?

Also, while yarn locks are great, they don't make sense for libraries, which shouldn't pin their dependencies (so downstream users can dedupe/&c.).

**Comment by steida** [comment]
> I'm not sure about that on the Flow side. If somebody not familiar with Flow wants to submit a PR to an existing file, what is he or she to do?

Install Nuclide in Atom and in Nuclide settings enable flow-bin, that's all. It's not even checked in npm test so he / she can't break anything.

**Comment by steida** [comment]
As for yarn.lock for libraries

https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by steida** [comment]
"The contributor’s burden

Now let’s talk a bit about the social side of not using lockfiles in libraries.

As mentioned previously, the majority of breaking changes that occur in library dependencies will be development dependencies.

Some percentage of these breaking changes will be caught and (hopefully) fixed by regular contributors. However, the remaining breaking changes will be caught by new or infrequent contributors.

Contributing to a project for the first time is a very intimidating experience for anyone who is not an open source veteran. If the first thing a potential new contributor runs into is a broken build or test suite, they could be so intimidated that they decide to forget about contributing back.

Even as someone who contributes to lots of open source projects, it’s a terrible thing to have to debug a build system for a few hours when you just want to fix a bug or add a small feature to a library."

**Comment by taion** [comment]
That only works as long as we don't use Flow for anything nontrivial here. If we do, then anybody writing code here has to deal with Flow. I do use Flow elsewhere, but for reduced barrier to entry, I don't think in general it makes sense for OSS projects unless there are real significant benefits, which there aren't.

I do in fact contribute to a lot of open source projects, and I've seldom had problems with unpinned dependencies in libraries. In fact I think there's an advantage to doing things this way to serve as a canary for potential incompatibilities for downstream uers.

**Comment by rosskevin** [comment]
@taion I appreciate that you are thinking about the barrier to entry, but I come at it from the opposite direction.

Flow would decrease the maintenance burden for owners/maintainers by providing greater confidence to merge PRs.  For newcomers, it will also provide quick feedback to them as they try to misuse those things common to owners/maintainers.  If a project were flow-typed, I know I can make a quick contribution and it will catch silly mistakes.

If this project maintains flow types to a good standard, this can only serve to provide clarity for those looking to use or contribute, and actually ease the barrier to entry.

**Comment by jquense** [comment]
i'm on @taions side here. Flow is only helpful to folks contributing if they already know it. for everyone else (most people) it means opening up another set of docs, struggling with type annotations and flows arcane error messages. heck i am familiar with flow, but will walk away from most libraries that use it rather then contribute because I often just don't have the time to faff around with something that isn't the fix i wanted to make.

**Comment by steida** [comment]
Are we talking about router made from expert for experts, since all folks will use react router forever because "it's so easy to have SwitchNamedAsRouter"?

**Comment by steida** [comment]
Please reconsider flow since it eases code navigation.

**Comment by steida** [comment]
Please merge it. I am beginner so I need easy code navigation to understand hot found works. 🐢

**Comment by taion** [comment]
I'm going to go ahead and close this for now. I don't want to use Flow here for the time being, and the Yarn changes may be irrelevant now with npm 5.

Sorry.

**Comment by rosskevin** [comment]
Before starting to convert my code to `found` + `found-relay`, I've been pouring over the documentation and code to create a flow libdef.  My previous code was flow typed to react router, so it made sense to create this libdef early so that it would catch errors quickly. 

Here's a gist of my first draft, once complete I may try to PR it to flow-typed.

https://gist.github.com/rosskevin/0a7e854ccc5cb126cd4410c7e1348000

**Comment by hannesj** [comment]
@rosskevin Did you ever get around finalizing the libdef? Would be nice to have the found included in the flow-typed repository.

**Comment by rosskevin** [comment]
No, I'm in the process of switching to typescript as we speak due to https://github.com/facebook/flow/issues/5382

I spent a lot of time on flow, and this ended up being to deal breaker.  

I'll look at typescript for found likely today.

Feel free to take what I have and improve or submit it.

**Pull request closed without merging**
