### PR TITLE
Tests (ActionTypes, BaseLink)

### PR DESCRIPTION
**Pull request by chentsulin**
I am not sure we should use `enzyme` here, but IMO it make tests easier to read. Another Question is that how should we mock match and router objects?

### CODE REVIEW

**Comment by taion** [comment]
Our house preference is actually for teaspoon, but they're similar enough. Will look at this in more detail when I get a chance.

**Comment by ctrlplusb** [comment]
I would highly recommend looking into integration of [`enzyme-to-json`](https://github.com/adriantoine/enzyme-to-json) and then make use of Jest's snapshot testing feature. :)

**Comment by chentsulin** [comment]
Rebased with master

**Comment by taion** [comment]
Thanks!

**Pull request merged**
