### PR TITLE
Allow custom resolvers

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by taion** [comment]
Do you think this is dramatically better than using `createFarceRouter`?

The reason I didn't allow this initially is because I wanted to avoid pulling in the code for the "basic" resolver here in cases where I'm using Relay.

If you are using Found Relay, maybe we can add a utility to Found Relay to allow this?

**Comment by jquense** [comment]
Yeah so it's just that the relay case involves a bunch of imports and config. Adding something to found relay is not a bad idea. Tbh i would imagine 90% of folks using found are here for relay, so maybe worth optimizing that getting started for that case

**Comment by taion** [comment]
It is just the resolver though \:

I dunno, this literally only saves you one import, though, no?

**Comment by jquense** [comment]
it saves a protocol import, remembering the name of the options, importing `createRender` to handle the error case. IDK it takes me 15min to figure out how to make a router here, switching between the two projects. Maybe found-relay should provide a basic Router component that also has something like an auth container included? That's like 90% of why i end up having to do all this stuff on projects

**Comment by jquense** [comment]
I think any createRouter is fine in FR, i don't mind specifying the protocol, but it feels like to much api to figure out when all i want to do is set the resolver on the browser.

**Comment by taion** [comment]
Yeah, like a `createBrowserRelayRouter`? Do you want to add it or should I? :p

**Pull request closed without merging**
