### PR TITLE
fix isActive on query

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by taion** [comment]
Let's do something like

```javascript
isEqual(matchQuery[key], value) ||
(value === undefined && !Object.prototype.hasOwnProperty.call(matchQuery, key))
```

**Comment by taion** [comment]
Did this just not handle the special logic I added to RR for using `undefined` to mean "this query arg must be empty"?

**Comment by jquense** [comment]
> Did this just not handle the special logic I added to RR for using undefined to mean "this query arg must be empty"?

I think so yeah.

**Comment by taion** [comment]
oops we should support that

**Comment by taion** [comment]
could you fix that real quick?

**Comment by jquense** [comment]
Sorry :P I'll get it in a bit

**Pull request merged**
