### PR TITLE
[WIP] feat: Add error boundary in router

### LINKED ISSUE #219: Add an ErrorBoundary to allow throwing HttpErrors when not resolving

### PR DESCRIPTION
**Pull request by taion**
Closes #219

### CODE REVIEW

**Comment by taion** [comment]
@jquense @itajaja thoughts here? i'm not really sure whether this is useful. throwing an exception in `render` seems less than perfect to me

**Comment by taion** [comment]
i mean, in a random component's `render` method

**Comment by jquense** [comment]
I think this should enable something that _looks_ nicer tho right e.g.

```
function Foo({ match }) {
	if (!match.params.userId) return <NotFound /> // or Redirect etc

}
```

which is kinda cool and like how the other routers seems to work now

**Comment by taion** [comment]
Right, so here it'd instead be `throw new HttpError(404)`, which I think makes more sense anyway.

But I think in practice for this sort of thing, you'd most often want to do it from `render` on the route, no? Or is the idea that this lets us elide the `if (!props) { return; }` bit?

**Comment by taion** [comment]
Huh, do errors in `render` always lead to console spam? In other words, is there no way to mark an error as handled in an error boundary, and suppress console output?

**Comment by taion** [comment]
Not going ahead for now. The console error spam means this isn't viable as a general thing.

**Pull request closed without merging**
