### PR TITLE
fix: Add some type definitions

### PR DESCRIPTION
**Pull request by hwwi**
Sorry about frequently open a PR.
But createMatchEnhancer was bothering me 😫

### CODE REVIEW

**Comment by taion** [comment]
No, thank _you_ for adding these!

**Comment by hwwi** [comment]
First, Sorry for my poor English.

I think that [getFarceResult function's return type](https://github.com/4Catalyzer/found/blob/b375a1f65ec4431e86163131bfa801ea5293ecd1/types/server/index.d.ts#L25) is not [Discriminated Unions](https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions), so infer is hard. 

So I used it this way...
`
interface FarceResult {
    status?: number;
    element?: React.ReactElement;
    redirect?: {
      url: string;
    };
  }
`

For the time being, I have excluded it from writing test code.
If you decide the direction, I will write continue.

**Comment by hwwi** [comment]
Any comments or thoughts on this?

**Comment by taion** [comment]
Sorry for the delay. I'll try to look at this and https://github.com/4Catalyzer/farce/pull/175 today.

**Pull request merged**
